[package]
name = "zz_native_rt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
base64 = "0.22"
regex = "1"
sha2 = { version = "0.10", features = ["oid"] }
hmac = "0.12"
subtle = "2"
getrandom = "0.3"
argon2 = "0.5"
bcrypt = "0.15"
rand_core = { version = "0.6", features = ["getrandom"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
rsa = "0.9"
serde_json = "1"
sysinfo = "0.30"
uuid = { version = "1", features = ["v4", "v7"] }
rustls = { workspace = true }
webpki-roots = "1"
rustls-pki-types = "1"

[dev-dependencies]
rcgen = "0.13"
