//! zz.lock parse/emit with checksum verification.
//!
//! Lockfile format:
//! ```toml
//! # This file is auto-generated by `zz`. DO NOT EDIT.
//! # Checksum: <sha256 of content below>
//! version = 1
//!
//! [[deps]]
//! name = "foo"
//! version = "1.2.3"
//! source = "registry"
//! hash = "abc123..."
//! ```

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::hash;

/// Header written at the top of every lockfile.
const LOCK_HEADER: &str = "# This file is auto-generated by `zz`. DO NOT EDIT.";

/// Lockfile version (for future format migrations).
pub const LOCK_VERSION: u32 = 1;

/// A fully resolved lockfile.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Lockfile {
    pub version: u32,
    pub deps: Vec<LockedDep>,
    /// Hash of the manifest's [dependencies] section when this lock was created.
    /// Used for short-circuit: if deps_match(), skip re-resolution.
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manifest_deps_hash: Option<String>,
    /// Checksum stored in header comment, verified on load.
    /// Not serialized to TOML (stored in comment header).
    #[serde(skip)]
    pub checksum: String,
}

/// A single locked dependency.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LockedDep {
    pub name: String,
    pub version: String,
    /// Source tag: `"registry"`, `"git+<url>#<sha>"`, or `"path:<rel>"`.
    pub source: String,
    /// CAS content hash.
    pub hash: String,
    /// Exact commit SHA (for git deps only).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub commit: Option<String>,
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::new()
    }
}

impl Lockfile {
    /// Create an empty lockfile.
    pub fn new() -> Self {
        Self {
            version: LOCK_VERSION,
            deps: Vec::new(),
            manifest_deps_hash: None,
            checksum: String::new(),
        }
    }

    /// Load a lockfile from disk. Verifies header checksum.
    pub fn load(path: &Path) -> Result<Self, String> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        Self::parse(&content)
    }

    /// Parse a lockfile from a string. Verifies header checksum.
    pub fn parse(s: &str) -> Result<Self, String> {
        // Extract checksum from header comment
        let checksum = extract_checksum(s);

        // Parse the TOML (skip header lines)
        let toml_content: String = s
            .lines()
            .filter(|l| !l.starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");

        let mut lockfile: Lockfile =
            toml::from_str(&toml_content).map_err(|e| format!("invalid zz.lock: {e}"))?;
        lockfile.checksum = checksum.unwrap_or_default();

        // Verify checksum if present
        if !lockfile.checksum.is_empty() {
            let body: String = s
                .lines()
                .filter(|l| !l.starts_with('#'))
                .collect::<Vec<_>>()
                .join("\n");
            let computed = hash::hash_bytes(body.trim().as_bytes());
            if computed != lockfile.checksum {
                return Err("zz.lock checksum mismatch\n\
                     hint: the lockfile may have been edited; run `zz install` to regenerate"
                    .to_string());
            }
        }

        Ok(lockfile)
    }

    /// Save the lockfile with a fresh checksum.
    pub fn save(&self, path: &Path) -> Result<(), String> {
        let body =
            toml::to_string_pretty(self).map_err(|e| format!("cannot serialize lockfile: {e}"))?;

        // Compute checksum over body only (header is decoration, not content).
        // Trim trailing whitespace to ensure consistent hashing across platforms.
        let checksum = hash::hash_bytes(body.trim().as_bytes());

        let content = format!("{LOCK_HEADER}\n# Checksum: {checksum}\n{body}");
        std::fs::write(path, content).map_err(|e| format!("cannot write {}: {e}", path.display()))
    }

    /// Verify the stored checksum matches current content.
    pub fn verify(&self, path: &Path) -> Result<bool, String> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        let stored = extract_checksum(&content).unwrap_or_default();
        if stored.is_empty() {
            return Ok(true); // No checksum to verify
        }
        // Extract body (everything after comment lines), trim for consistency
        let body: String = content
            .lines()
            .filter(|l| !l.starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        let computed = hash::hash_bytes(body.trim().as_bytes());
        Ok(computed == stored)
    }

    /// Check if deps section of manifest matches what lock was built from.
    pub fn deps_match(&self, manifest_deps_hash: &str) -> bool {
        match &self.manifest_deps_hash {
            Some(stored) => stored == manifest_deps_hash,
            None => false, // No stored hash → must re-resolve
        }
    }

    /// Record the manifest deps hash (call after resolving).
    pub fn set_manifest_deps_hash(&mut self, hash: String) {
        self.manifest_deps_hash = Some(hash);
    }

    /// Find a locked dep by name.
    pub fn find(&self, name: &str) -> Option<&LockedDep> {
        self.deps.iter().find(|d| d.name == name)
    }

    /// Add or update a dependency.
    pub fn upsert(&mut self, dep: LockedDep) {
        if let Some(existing) = self.deps.iter_mut().find(|d| d.name == dep.name) {
            *existing = dep;
        } else {
            self.deps.push(dep);
        }
    }

    /// Remove a dependency by name.
    pub fn remove(&mut self, name: &str) -> bool {
        let len_before = self.deps.len();
        self.deps.retain(|d| d.name != name);
        self.deps.len() < len_before
    }
}

/// Extract the checksum from a `# Checksum: <hex>` header line.
fn extract_checksum(content: &str) -> Option<String> {
    for line in content.lines() {
        if let Some(rest) = line.strip_prefix("# Checksum: ") {
            let checksum = rest.trim().to_string();
            if !checksum.is_empty() {
                return Some(checksum);
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;

    fn tmp_dir(name: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("zz_lock_test_{name}_{}", std::process::id()));
        let _ = fs::remove_dir_all(&d);
        fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn round_trip() {
        let mut lock = Lockfile::new();
        lock.upsert(LockedDep {
            name: "foo".into(),
            version: "1.2.3".into(),
            source: "registry".into(),
            hash: "abc123".into(),
            commit: None,
        });
        lock.upsert(LockedDep {
            name: "bar".into(),
            version: "2.0.0".into(),
            source: "git+https://github.com/user/repo#def456".into(),
            hash: "789".into(),
            commit: Some("def456".into()),
        });

        let d = tmp_dir("round_trip");
        let path = d.join("zz.lock");
        lock.save(&path).unwrap();
        let loaded = Lockfile::load(&path).unwrap();

        // Compare logical content (checksum is skip-serialized, so compare separately)
        assert_eq!(lock.version, loaded.version);
        assert_eq!(lock.deps, loaded.deps);
        assert_eq!(lock.manifest_deps_hash, loaded.manifest_deps_hash);
        assert!(
            !loaded.checksum.is_empty(),
            "loaded lockfile should have checksum"
        );

        let _ = fs::remove_dir_all(&d);
    }

    #[test]
    fn checksum_detects_edit() {
        let mut lock = Lockfile::new();
        lock.upsert(LockedDep {
            name: "foo".into(),
            version: "1.0.0".into(),
            source: "registry".into(),
            hash: "abc".into(),
            commit: None,
        });

        let d = tmp_dir("checksum");
        let path = d.join("zz.lock");
        lock.save(&path).unwrap();

        // Tamper with the actual TOML content (not a comment — comments are filtered out)
        let mut content = fs::read_to_string(&path).unwrap();
        content.push_str("\nversion = 99\n"); // corrupt the TOML body
        fs::write(&path, &content).unwrap();

        // Verify should fail
        let result = Lockfile::load(&path);
        assert!(result.is_err(), "tampered lockfile should fail to load");
        let _ = fs::remove_dir_all(&d);
    }

    #[test]
    fn deps_match_shortcircuit() {
        let mut lock = Lockfile::new();
        lock.upsert(LockedDep {
            name: "foo".into(),
            version: "1.0.0".into(),
            source: "registry".into(),
            hash: "abc".into(),
            commit: None,
        });

        // Create manifest with same deps
        let mut deps = std::collections::HashMap::new();
        deps.insert(
            "foo".to_string(),
            crate::manifest::DepSpec::Version("^1.0".into()),
        );
        let manifest = crate::manifest::Manifest {
            package: crate::manifest::PackageSpec {
                name: "test".into(),
                version: "0.1.0".into(),
            },
            dependencies: deps,
        };

        let manifest_hash = manifest.deps_hash();

        // Before setting hash: no match
        assert!(!lock.deps_match(&manifest_hash));

        // After setting hash: match
        lock.set_manifest_deps_hash(manifest_hash.clone());
        assert!(lock.deps_match(&manifest_hash));

        // Different hash: no match
        assert!(!lock.deps_match("different_hash"));
    }

    #[test]
    fn find_dep() {
        let mut lock = Lockfile::new();
        lock.upsert(LockedDep {
            name: "foo".into(),
            version: "1.0.0".into(),
            source: "registry".into(),
            hash: "abc".into(),
            commit: None,
        });

        assert!(lock.find("foo").is_some());
        assert!(lock.find("bar").is_none());
    }

    #[test]
    fn upsert_updates_existing() {
        let mut lock = Lockfile::new();
        lock.upsert(LockedDep {
            name: "foo".into(),
            version: "1.0.0".into(),
            source: "registry".into(),
            hash: "abc".into(),
            commit: None,
        });
        lock.upsert(LockedDep {
            name: "foo".into(),
            version: "2.0.0".into(),
            source: "registry".into(),
            hash: "def".into(),
            commit: None,
        });

        assert_eq!(lock.deps.len(), 1);
        assert_eq!(lock.find("foo").unwrap().version, "2.0.0");
    }

    #[test]
    fn remove_dep() {
        let mut lock = Lockfile::new();
        lock.upsert(LockedDep {
            name: "foo".into(),
            version: "1.0.0".into(),
            source: "registry".into(),
            hash: "abc".into(),
            commit: None,
        });

        assert!(lock.remove("foo"));
        assert!(lock.find("foo").is_none());
        assert!(!lock.remove("foo")); // already removed
    }

    #[test]
    fn empty_lockfile() {
        let d = tmp_dir("empty");
        let path = d.join("zz.lock");
        let lock = Lockfile::new();
        lock.save(&path).unwrap();
        let loaded = Lockfile::load(&path).unwrap();
        assert_eq!(loaded.deps.len(), 0);
        let _ = fs::remove_dir_all(&d);
    }
}
