[package]
name = "zz_pm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ZZ package manager — CAS, resolution, lockfile, build cache"

[dependencies]
semver = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
rayon = { workspace = true }
memmap2 = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
